# Generated by Django 5.1.3 on 2026-08-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_seochangehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOAuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('technical_score', models.IntegerField(default=0)),
                ('content_score', models.IntegerField(default=0)),
                ('metadata_score', models.IntegerField(default=0)),
                ('schema_score', models.IntegerField(default=0)),
                ('issues', models.JSONField(default=list)),
                ('checks', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='api.pageseo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
