# Generated by Django 5.1.3 on 2026-08-27 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_seoauditresult'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_mode',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('dynamic', 'Dynamic')], default='legacy', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ContentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('page_type', models.CharField(default='generic', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('seo_path', models.CharField(blank=True, max_length=255)),
                ('body_mode', models.CharField(choices=[('legacy', 'Legacy'), ('dynamic', 'Dynamic')], default='dynamic', max_length=10)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['path'],
            },
        ),
        migrations.CreateModel(
            name='DynamicSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('section_type', models.CharField(max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('content', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['content_type', 'object_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SectionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(default='image', max_length=100)),
                ('image_prompt', models.TextField(blank=True)),
                ('alt_override', models.CharField(blank=True, max_length=255)),
                ('required', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.uploadedimage')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api.dynamicsection')),
            ],
        ),
        migrations.AddIndex(
            model_name='dynamicsection',
            index=models.Index(fields=['content_type', 'object_id', 'order'], name='api_dynamic_content_1a7377_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sectionmedia',
            unique_together={('section', 'slot')},
        ),
    ]
