# Generated by Django 5.1.3 on 2026-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_blogpost_body_mode_alter_blogpost_slug_contentpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='caption',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='checksum',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='focal_x',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='focal_y',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='format',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='license',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='usage',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
