# Generated by Django 5.1.3 on 2026-08-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_uploadedimage_alt_text_uploadedimage_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsubmission',
            name='ip_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='referer',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='user_agent',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
