# Generated by Django 5.1.3 on 2026-08-27 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_formsubmission_ip_hash_formsubmission_is_spam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redirect',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='redirect',
            name='hit_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='redirect',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='last_hit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redirect',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='redirect',
            name='status_code',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(301, '301 Moved Permanently'), (302, '302 Found'), (307, '307 Temporary Redirect'), (308, '308 Permanent Redirect')], null=True),
        ),
    ]
