# Generated by Django 5.1.3 on 2026-10-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_redirect_created_at_redirect_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicsection',
            name='draft_content',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
