# Generated by Django 5.1.3 on 2026-10-09 08:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_dynamicsection_draft_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('action', models.CharField(max_length=40)),
                ('target', models.CharField(blank=True, max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_hash', models.CharField(max_length=64)),
                ('choice', models.JSONField(default=dict)),
                ('banner_version', models.CharField(blank=True, max_length=20)),
                ('at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_norm', models.CharField(blank=True, db_index=True, max_length=254)),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('name_locked', models.BooleanField(default=False)),
                ('status', models.CharField(default='new', max_length=40)),
                ('status_history', models.JSONField(blank=True, default=list)),
                ('notes', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('opt_in_at', models.DateTimeField(blank=True, null=True)),
                ('opt_in_source', models.JSONField(blank=True, default=dict)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('first_source', models.JSONField(blank=True, default=dict)),
                ('last_source', models.JSONField(blank=True, default=dict)),
                ('intents', models.JSONField(blank=True, default=dict)),
                ('segment', models.CharField(blank=True, max_length=60)),
                ('stages', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('value', models.FloatField(default=0)),
                ('visits', models.IntegerField(default=0)),
                ('vid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_client', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('retain_until', models.DateTimeField(blank=True, null=True)),
                ('merge_suggestions', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('kind', models.CharField(default='custom', max_length=10)),
                ('rule', models.JSONField(blank=True, default=dict)),
                ('sync_to', models.JSONField(blank=True, default=list)),
                ('remote', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ErasureTombstone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=120, unique=True)),
                ('level', models.CharField(default='warning', max_length=10)),
                ('message', models.TextField()),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(choices=[('google', 'google'), ('meta', 'meta'), ('tiktok', 'tiktok'), ('linkedin', 'linkedin'), ('google_ads', 'google_ads')], max_length=20, unique=True)),
                ('status', models.CharField(default='not_connected', max_length=20)),
                ('account', models.JSONField(blank=True, default=dict)),
                ('secret', models.TextField(blank=True)),
                ('secret_hint', models.CharField(blank=True, max_length=12)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_ok_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(default='manual', max_length=20)),
                ('mode', models.CharField(default='in_browser', max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('scope', models.JSONField(blank=True, default=list)),
                ('tests', models.JSONField(blank=True, default=list)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('nonce', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='consent',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='event_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='is_test',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='api.contact'),
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=60)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.contact')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='EventOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=60)),
                ('params', models.JSONField(default=dict)),
                ('consent', models.JSONField(default=dict)),
                ('identifiers', models.JSONField(default=dict)),
                ('context', models.JSONField(default=dict)),
                ('tools_pending', models.JSONField(default=list)),
                ('results', models.JSONField(default=dict)),
                ('attempts', models.IntegerField(default=0)),
                ('next_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_test', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'unique_together': {('event_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TrackingDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=60)),
                ('conversion_id', models.CharField(blank=True, max_length=60)),
                ('intent', models.CharField(blank=True, max_length=60)),
                ('count', models.IntegerField(default=0)),
                ('test_count', models.IntegerField(default=0)),
                ('last_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('date', 'name', 'conversion_id', 'intent')},
            },
        ),
        migrations.CreateModel(
            name='TrackingSyncItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool', models.CharField(max_length=20)),
                ('kind', models.CharField(max_length=40)),
                ('plan_id', models.CharField(max_length=60)),
                ('remote_id', models.CharField(blank=True, max_length=200)),
                ('desired_hash', models.CharField(blank=True, max_length=64)),
                ('remote_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('tool', 'kind', 'plan_id')},
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_id', models.CharField(max_length=60)),
                ('tool', models.CharField(blank=True, max_length=20)),
                ('step', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='api.verificationrun')),
            ],
        ),
    ]
