"""Google Tag Manager: build the container content for this plan (variables,
one regex custom-event trigger, GA4 tags, consent settings) — as an
importable JSON file, or pushed through the GTM API into a new workspace.
Publishing stays a deliberate click (other people's tags may live there)."""

import json

from . import base, google_auth

API = "https://tagmanager.googleapis.com/tagmanager/v2"
SCOPES = ["https://www.googleapis.com/auth/tagmanager.edit.containers",
          "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
          "https://www.googleapis.com/auth/tagmanager.publish"]
PARAMS = ["page_path", "page_type", "intent", "segment", "stage", "block", "cta_label", "cta_target", "nav_area", "nav_label",
          "percent", "faq_id", "faq_topic", "form_name", "field", "last_field", "method", "link_domain", "file_ext", "file_name",
          "conversion_id", "conversions", "tier", "value", "currency", "event_id"]
EVENTS = ["page_view", "cta_click", "nav_click", "section_view", "scroll_depth", "service_engaged", "faq_open", "form_start",
          "form_error", "form_abandon", "generate_lead", "contact_click", "outbound_click", "file_download", "search", "conversion"]


def container(plan, measurement_id):
    """GTM container export (exportFormatVersion 2) for this plan."""
    var = lambda name: {"name": f"dlv - {name}", "type": "v", "parameter": [
        {"type": "INTEGER", "key": "dataLayerVersion", "value": "2"}, {"type": "BOOLEAN", "key": "setDefaultValue", "value": "false"},
        {"type": "TEMPLATE", "key": "name", "value": name}]}
    variables = [dict(var(p), variableId=str(i + 1)) for i, p in enumerate(PARAMS)]
    trigger = {"triggerId": "1", "name": "CMS events", "type": "CUSTOM_EVENT",
               "customEventFilter": [{"type": "MATCH_REGEX", "parameter": [
                   {"type": "TEMPLATE", "key": "arg0", "value": "{{_event}}"},
                   {"type": "TEMPLATE", "key": "arg1", "value": "^(" + "|".join(EVENTS) + ")$"}]}]}
    conv_trigger = {"triggerId": "2", "name": "CMS conversions", "type": "CUSTOM_EVENT",
                    "customEventFilter": [{"type": "EQUALS", "parameter": [
                        {"type": "TEMPLATE", "key": "arg0", "value": "{{_event}}"}, {"type": "TEMPLATE", "key": "arg1", "value": "conversion"}]}]}
    event_params = {"type": "LIST", "key": "eventSettingsTable", "list": [
        {"type": "MAP", "map": [{"type": "TEMPLATE", "key": "parameter", "value": p},
                                {"type": "TEMPLATE", "key": "parameterValue", "value": "{{dlv - " + p + "}}"}]} for p in PARAMS]}
    consent = {"consentStatus": "NEEDED", "consentType": {"type": "LIST", "list": [{"type": "TEMPLATE", "value": "analytics_storage"}]}}
    tags = [
        {"tagId": "1", "name": "CMS - Google tag", "type": "googtag", "parameter": [{"type": "TEMPLATE", "key": "tagId", "value": measurement_id}],
         "firingTriggerId": ["2147479573"], "consentSettings": consent},
        {"tagId": "2", "name": "CMS - GA4 events", "type": "gaawe", "parameter": [
            {"type": "TEMPLATE", "key": "eventName", "value": "{{Event}}"},
            {"type": "TEMPLATE", "key": "measurementIdOverride", "value": measurement_id}, event_params],
         "firingTriggerId": ["1"], "consentSettings": consent},
        {"tagId": "3", "name": "CMS - GA4 conversion events", "type": "gaawe", "parameter": [
            {"type": "TEMPLATE", "key": "eventName", "value": "cv_{{dlv - conversion_id}}"},
            {"type": "TEMPLATE", "key": "measurementIdOverride", "value": measurement_id}, event_params],
         "firingTriggerId": ["2"], "consentSettings": consent},
    ]
    return {"exportFormatVersion": 2, "exportTime": "", "containerVersion": {
        "name": f"dynamic-cms plan v{plan.get('version', 0)}", "description": "Generated by dynamic-cms (Site tools → Tracking).",
        "tag": tags, "trigger": [trigger, conv_trigger], "variable": variables,
        "builtInVariable": [{"type": "EVENT", "name": "Event"}]}}


def push(plan, conn, measurement_id):
    """Create a workspace with the container content. Returns the workspace
    path; publishing is a separate, explicit step (publish())."""
    acct = conn["account"]
    parent = f"accounts/{acct['gtmAccountId']}/containers/{acct['gtmContainerId']}"
    h = {"Authorization": f"Bearer {google_auth.access_token(conn, SCOPES)}"}
    _, ws = base.http_json("POST", f"{API}/{parent}/workspaces", {"name": f"dynamic-cms v{plan.get('version', 0)}"}, headers=h)
    content = container(plan, measurement_id)["containerVersion"]
    ids = {}
    for v in content["variable"]:
        body = {k: v[k] for k in ("name", "type", "parameter")}
        base.http_json("POST", f"{API}/{ws['path']}/variables", body, headers=h)
    for t in content["trigger"]:
        _, res = base.http_json("POST", f"{API}/{ws['path']}/triggers", {k: t[k] for k in ("name", "type", "customEventFilter")}, headers=h)
        ids[t["triggerId"]] = res.get("triggerId")
    for tag in content["tag"]:
        body = {k: tag[k] for k in ("name", "type", "parameter", "consentSettings")}
        body["firingTriggerId"] = [ids.get(t, t) for t in tag["firingTriggerId"]]
        base.http_json("POST", f"{API}/{ws['path']}/tags", body, headers=h)
    return ws["path"]


def publish(workspace_path, conn):
    h = {"Authorization": f"Bearer {google_auth.access_token(conn, SCOPES)}"}
    _, version = base.http_json("POST", f"{API}/{workspace_path}:create_version", {"name": "dynamic-cms"}, headers=h)
    path = (version.get("containerVersion") or {}).get("path")
    if not path:
        raise base.Permanent(f"GTM couldn't create a version: {json.dumps(version.get('compilerError') or version)[:300]}")
    base.http_json("POST", f"{API}/{path}:publish", {}, headers=h)
    return path


def send(event, conn):
    return {"ok": False, "skipped": True, "detail": "GTM runs in the browser only."}


def desired(plan):
    return []
